spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: eth

  datasource:
    url: jdbc:mysql://localhost:3306/dockerby
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  token:
    header: Authorization
    issuer: NoBadDonation
    secret: 41NTQUZZLTYtRGVhamVvbi0xLUIxMDUtaGVyZS1Jcy1Oby1CYWQtRG9uYXRpb24K # "dockerby" Base64 Encoding 대문자 8, 소문자 4
    expirySeconds: 86400

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

uploadPath:
  path: "./fileData/"